### ISSUE TITLE
handle cofactors differently than metabolites

### ISSUE THREAD

**Issue by cardiffryan** [carothersresearch/ODBM#2]
In species definition, create different types for metabolite and cofactor and treat them differently when writing rate laws (rates should not be dependent on cofactors, assuming in excess)

**Comment by cardiffryan** [comment]
Still want cofactors to be included in chemical equation but NOT used in rate law.
I don't want to include ATP/ADP in substrate/products, but I want it in my chemical equation (not rate)

**Comment by dalbabur** [comment]
my workaround was to have "Substrates", "Cofactors", and "Products", where cofactors are just substrates not involved in the the reaction rate. that way you can write something like:
`allS = ' + '.join(map(fmt, [*S,*C]))   # to get both substrates and cofactors to write in the equation,
and then just use S for writing the reaction rate`
